
import java.util.HashMap;
import java.util.Map;


public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    Pila pil;

    public Formulario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTamaño = new javax.swing.JTextField();
        btnCrearPila = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtCodigoMateria = new javax.swing.JTextField();
        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        btnApilar = new javax.swing.JButton();
        btnDesapilar = new javax.swing.JButton();
        btnVacia = new javax.swing.JButton();
        btnLlena = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResultado = new javax.swing.JTextArea();
        btnAprobados = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNotaSup = new javax.swing.JTextField();
        btnNumReprobados = new javax.swing.JButton();
        btnProomedioCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manejo de Pilas");

        jLabel2.setText("Realizado  por: Jhordan Huera");

        jLabel3.setText("Ingrese el tamaño de la Pila:");

        btnCrearPila.setText("Crear Pila");
        btnCrearPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPilaActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese  Cedula");

        jLabel5.setText("Ingrese el Código de Materia:");

        jLabel6.setText("Ingrese Nota 1:");

        jLabel7.setText("Ingrese Nota 2:");

        btnApilar.setText("Apilar");
        btnApilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApilarActionPerformed(evt);
            }
        });

        btnDesapilar.setText("Desapilar");
        btnDesapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesapilarActionPerformed(evt);
            }
        });

        btnVacia.setText("Vacia");
        btnVacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciaActionPerformed(evt);
            }
        });

        btnLlena.setText("Llena");
        btnLlena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenaActionPerformed(evt);
            }
        });

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        txaResultado.setColumns(20);
        txaResultado.setRows(5);
        jScrollPane1.setViewportView(txaResultado);

        btnAprobados.setText("Aprobados");
        btnAprobados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobadosActionPerformed(evt);
            }
        });

        jLabel8.setText("Ingresar Nota Supletorio:");

        txtNotaSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaSupActionPerformed(evt);
            }
        });

        btnNumReprobados.setText("Numero Reprobados");
        btnNumReprobados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumReprobadosActionPerformed(evt);
            }
        });

        btnProomedioCurso.setText("Promedio Curso");
        btnProomedioCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProomedioCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(btnVacia)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnLlena))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(btnApilar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDesapilar)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAprobados)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnReporte)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNotaSup, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(btnProomedioCurso))
                                            .addComponent(btnNumReprobados))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(44, 44, 44)
                                        .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addComponent(btnCrearPila)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearPila))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel6))
                            .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNotaSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApilar)
                    .addComponent(btnDesapilar)
                    .addComponent(btnNumReprobados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVacia)
                    .addComponent(btnLlena)
                    .addComponent(btnProomedioCurso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporte)
                    .addComponent(btnAprobados)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApilarActionPerformed
        // TODO add your handling code here:
        if (!pil.Llena()) {
            String ced = this.txtCedula.getText();
            String codM = this.txtCodigoMateria.getText();
            int n1 = Integer.parseInt(this.txtNota1.getText());
            int n2 = Integer.parseInt(this.txtNota2.getText());
            int sup = Integer.parseInt(this.txtNotaSup.getText());
            Notas not = new Notas(ced, codM, n1, n2, sup);
            pil.Apilar(not);
        } else {
            this.txaResultado.setText("No puedes apilar, la pila esta llena....");
        }
    }//GEN-LAST:event_btnApilarActionPerformed

    private void btnCrearPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPilaActionPerformed
        // TODO add your handling code here:
        int t = Integer.parseInt(this.txtTamaño.getText());
        pil = new Pila(t);
        this.txaResultado.setText("La pila fue creada satisfactoriamente..........");

    }//GEN-LAST:event_btnCrearPilaActionPerformed

    private void btnDesapilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesapilarActionPerformed
        // TODO add your handling code here:
        if (!pil.Vacia()) {
            Object aux = pil.Desapilar();
            Notas not = (Notas) aux;
            this.txaResultado.setText(not.getCedula() + " " + not.getCodMateria() + " "
                    + not.getNota1() + " " + not.getNota2());
        } else {
            this.txaResultado.setText("No se puede desapilar, Pila Vacia......");
        }
    }//GEN-LAST:event_btnDesapilarActionPerformed

    private void btnVaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciaActionPerformed
        // TODO add your handling code here:
        boolean r = pil.Vacia();
        if (r == true)
            this.txaResultado.setText("La pila esta Vacia");
        else
            this.txaResultado.setText("La pila no esta vacia");
    }//GEN-LAST:event_btnVaciaActionPerformed

    private void btnLlenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenaActionPerformed
        // TODO add your handling code here:
        boolean r = pil.Llena();
        if (r) {
            this.txaResultado.setText("La pila se encuentra llena");
        } else
            this.txaResultado.setText("La pila no esta llena todavia...");
    }//GEN-LAST:event_btnLlenaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        String s = pil.Reporte();
        this.txaResultado.setText(s);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnAprobadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobadosActionPerformed
        // TODO add your handling code here:
        Pila pilAux = new Pila(pil.getTamanio());
        String r = "";
        Notas not;

        String codigoM = txtCodigoMateria.getText();
        while (!pil.Vacia()) {
            not = (Notas) pil.Desapilar();
            pilAux.Apilar(not);
            if (not.getCodMateria().equals(codigoM)) {
                if (not.getNota1() + not.getNota2() >= 14
                        || not.getNota1() + not.getNota2() + not.getNotaSup() >= 21) {
                    r += not.getCedula() + " " + not.getCodMateria() + " " + not.getNota1()
                            + " " + not.getNota2() + " " + not.getNotaSup() + "\n";
                }
            }
        }

        txaResultado.setText(r);
        while (!pilAux.Vacia()) {
            pil.Apilar(pilAux.Desapilar());
        }
    }//GEN-LAST:event_btnAprobadosActionPerformed

    private void txtNotaSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaSupActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtNotaSupActionPerformed

    private void btnNumReprobadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumReprobadosActionPerformed
        // TODO add your handling code here:
        Pila pilAux = new Pila(pil.getTamanio());
        String r = "";
        Notas not;
        int i = 0;
        String codigoM = txtCodigoMateria.getText();
        while (!pil.Vacia()) {
            not = (Notas) pil.Desapilar();
            pilAux.Apilar(not);
            if (not.getCodMateria().equals(codigoM)) {
                if (not.getNota1() + not.getNota2() < 11
                        || not.getNota1() + not.getNota2() + not.getNotaSup() < 21) {
                    i++;
                }
            }
        }
        r += "Reprobados: " + i;
        txaResultado.setText(r);
        while (!pilAux.Vacia()) {
            pil.Apilar(pilAux.Desapilar());
        }
    }//GEN-LAST:event_btnNumReprobadosActionPerformed

    private void btnProomedioCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProomedioCursoActionPerformed
        // TODO add your handling code here:
        try {
            Pila pAux = new Pila(pil.getTamanio());
            Notas not;
            int contEstudiantes = 0;
            String resultado = "";
            HashMap<String, Integer> aprobadosPorMateria = new HashMap<String, Integer>();
            HashMap<String, Double> promedioPorMateria = new HashMap<String, Double>();

            while (!pil.Vacia()) {
                contEstudiantes++;
                not = (Notas) pil.Desapilar();
                pAux.Apilar(not);
                double promedioEstudiante = (not.getNota1() + not.getNota2()) / 2.0;
                double sumaPromediosMateria = promedioPorMateria.getOrDefault(not.getCodMateria(), 0.0);
                sumaPromediosMateria += promedioEstudiante;
                promedioPorMateria.put(not.getCodMateria(), sumaPromediosMateria);
                int aprobadosEnMateria = aprobadosPorMateria.getOrDefault(not.getCodMateria(), 0);
                aprobadosPorMateria.put(not.getCodMateria(), aprobadosEnMateria + 1);
            }

            String resultadoMaterias = "";

            for (Map.Entry<String, Integer> entry : aprobadosPorMateria.entrySet()) {
                String codMateria = entry.getKey();
                int numEstudiantes = entry.getValue();
                double sumaPromedios = promedioPorMateria.get(codMateria);
                double promedioMateria = sumaPromedios / numEstudiantes;
                resultadoMaterias += "Promedio de la Materia " + codMateria + ": " + promedioMateria + " (" + numEstudiantes + " estudiantes)\n";
            }
            if (contEstudiantes > 0) {
                txaResultado.setText("El promedio total por materia: \n" + resultado + "\n" + resultadoMaterias);
            } else {
                txaResultado.setText("Pila vacia");
            }

            while (!pAux.Vacia()) {
                not = (Notas) pAux.Desapilar();
                pil.Apilar(not);
            }
        } catch (Exception e) {
            txaResultado.setText("Pila vacia");
        }
    }//GEN-LAST:event_btnProomedioCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApilar;
    private javax.swing.JButton btnAprobados;
    private javax.swing.JButton btnCrearPila;
    private javax.swing.JButton btnDesapilar;
    private javax.swing.JButton btnLlena;
    private javax.swing.JButton btnNumReprobados;
    private javax.swing.JButton btnProomedioCurso;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnVacia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaResultado;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigoMateria;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNotaSup;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
}
